gokargo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('', include(('home.urls', 'home'), namespace="home")),
    path('admin/', admin.site.urls),
]

home/urls.py
from django.conf.urls import url
from .views import index, submitted_data

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^submit-data$', submitted_data, name='submit_data'),
]

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms

class FileFieldForm(forms.Form):
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

home/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
from django.urls import reverse
from django.http import JsonResponse
from gokargo.classes.utils import *
from gokargo import solver
from io import StringIO

dataSolve = {} # Solve result

def index (request):
    return render(request, "home.html", {})

def submitted_data (request):
    if request.method == "POST" and 'file-cargo' in request.FILES\
        and 'file-flight' in request.FILES:
        try:
            cargo_string = StringIO(read_file(request.FILES.get('file-cargo')))
            flight_string = StringIO(read_file(request.FILES.get('file-flight')))
            cargos, flights = parse_csv(cargo_string, flight_string)
            cost, result = solver.get_assignments(cargos, flights)
            dataSolve = convert_to_json(cargos, flights, result, cost)
            return JsonResponse(dataSolve)
        except InputError as e:
            return HttpResponse(status=400, content=e.value)
    return HttpResponse(status=400, content="Bad Request.")

home/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>GoKargo - Beranda</title>
    <link rel=stylesheet href="{% static 'bootstrap-4.1.1.min.css' %}">
    <link rel=stylesheet href="{% static 'bootstrap-grid-4.1.1.min.css' %}">
    <link rel=stylesheet href="{% static 'bootstrap-reboot-4.1.1.min.css' %}">
    <link rel=stylesheet href="{% static 'vis.min.css' %}">
    <link rel=stylesheet href="{% static 'main.css' %}">
    <link rel="icon" type="image/png" href="{% static 'favicon.png' %}">
</head>
<body>
    <div class="logo-cnt">
      <img src="{% static 'gokargo-1000px.png' %}">
      <h1>GoKargo</h1>
      <h2>Solusi masalah kargo Anda.</h2>
    </div>
    <div class="container">
      <h3>3 langkah sederhana</h3>
      <form class="box" id="form-cargo" enctype="multipart/form-data" url="{% url 'home:submit_data' %}">
        <div class="box__input step" id="prog-cargo">
          <div class="step-cnt">1</div>
          <div class="step-progress">
            <div class="step-progress-bar"></div>
          </div>
          <div class="step-card">
            <div class="step-title">Pilih berkas CSV kargo</div>
            <div class="step-desc">Format data CSV:
              <ol>
                <li>ID kargo</li>
                <li>Destinasi</li>
                <li>Berat (dalam kg)</li>
                <li><i>Deadline</i> pengiriman dalam format DD-MM-YYYY h:m:s</li>
              </ol>
            </div>
            <div class="step-file no-file">Tidak ada berkas dipilih</div>
            <label for="file-cargo">Pilih</label>
          </div>
          <input class="box__file" type="file" id="file-cargo" name="file-cargo" />
        </div>
        <div class="box__input step" id="prog-flight">
          <div class="step-cnt">2</div>
          <div class="step-progress">
            <div class="step-progress-bar"></div>
          </div>
          <div class="step-card">
            <div class="step-title">Pilih berkas CSV penerbangan</div>
            <div class="step-desc">Format data CSV:
              <ol>
                <li>Nomor penerbangan</li>
                <li>Destinasi</li>
                <li>Waktu keberangkatan dalam format DD-MM-YYYY h:m:s</li>
                <li>Kapasitas maksimum pesawat (dalam kg)</li>
              </ol>
            </div>
            <div class="step-file no-file">Tidak ada berkas dipilih</div>
            <label for="file-flight">Pilih</label>
          </div>
          <input class="box__file" type="file" id="file-flight" name="file-flight" />
        </div>
        <div class="step" id="prog-upload">
          <div class="step-cnt">3</div>
          <div class="step-progress">
            <div class="step-progress-bar"></div>
          </div>
          <div class="step-card">
            <button id="submit" type="submit" class="box__button" disabled>Unggah!</button>
            <div class="step-desc">Dan tunggu hasil prosesnya</div>
            <div id="msg"><strong></strong><span class="content"></span></div>
          </div>
        </div>
      </form>
      <div class="result">
        <div class="graph">
        <h3>Hasil:</h3>
        <div id="gokargo-result" class="disabled"></div>
        </div>
        <p>Legenda:</p><div id="legend-net"></div>
        <p><i>Performance measure </i>: <span id="gokargo-cost">-</span></p>
        <p>Hasil <i>solve</i> dalam CSV:</p>
        <div id="gokargo-csv"></div>
      </div>
    </div>
  <div class="container">
    <div class="row">
      <div class="col-md-12 mt-3">
        <p class="text-center">Copyright © Artificial Ilkom 2018</p>
      </div>
    </div>
  </div>
</body>
<script type=application/javascript src="{% static 'jquery-3.3.1.min.js' %}"></script>
<script type=application/javascript src="{% static 'popper.min.js' %}"></script>
<script type=application/javascript src="{% static 'bootstrap-4.1.1.bundle.min.js' %}"></script>
<script type=application/javascript src="{% static 'jquery.easing.min.js' %}"></script>
<script type="text/javascript" src="{% static 'vis.min.js' %}"></script>
<script type="text/javascript" src="{% static 'number-format.js' %}"></script>
<script type="text/javascript" src="{% static 'main-network.js' %}"></script>
<script>
test = {};
(function($, window, document, undefined) {
  
  var container = $('#gokargo-result');
  var container_l = $('#legend-net');
  var ret = initialize_network(container, container_l);
  var network = ret['network'];
  var network_l = ret['network_l'];
  
  $.ajaxSetup({
    beforeSend: function(xhr, settings) {
      function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
          var cookies = document.cookie.split(';');
          for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
              cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
              break;
            }
          }
        }
        return cookieValue;
      }
      if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
        // Only send the token to relative URLs i.e. locally.
        xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
      }
    }
  });
  
  var nofile = 'Tidak ada berkas dipilih';
  
  var clear_message = function() {
    $("#msg").removeClass();
    $('#msg').fadeOut({'duration': 100});
  }
  
  var set_message = function(msgType, msgName, msgText) {
    $('#msg').fadeIn({'duration': 100});
    $('#msg').addClass(msgType);
    $('#msg > strong').text(msgName + ' ');
    $('#msg > .content').text(msgText);
  }
  
  var uploadbar = $("#prog-upload .step-progress-bar");
  var submit_button = $("#submit");
  var checkFileExists = function() {
    var flightcnt = $('#file-flight').prop("files").length;
    var cargocnt = $('#file-cargo').prop("files").length;
    return flightcnt + cargocnt == 2;
  }
  var enableButtonProperly = function() {
    if (checkFileExists()) {
      submit_button.removeAttr('disabled');
    } else {
      submit_button.prop('disabled', 'true');
    }
  }
  
  $('.box').each(function() {
    var $form = $(this),
      $box_inputs = $form.find('.box__input'),
      urlSubmit = $(this).attr('url')

    $box_inputs.each(function() {
      var $box = $(this),
        $input = $box.find('input[type="file"]'),
        $label = $box.find('.step-file'),
        $loadbar = $box.find('.step-progress-bar'),

        showFile = function(f) {
          if (f.length > 0) {
            var namefile = f[0].name;
            if (namefile.length > 30) {
              namefile = namefile.substring(0,30) + "..."
            }
            $label.removeClass('no-file');
            $label.text('"' + namefile + '"');
            $loadbar.removeClass('fail');
            $loadbar.addClass('success');
          } else {
            $label.addClass('no-file');
            $label.text(nofile);
            $loadbar.removeClass('success');
            $loadbar.addClass('fail');
          }
        };
        
      $input.on('click', function(e) {
        clear_message();
        uploadbar.get(0).className = 'step-progress-bar';
      });

      $input.on('change', function(e) {
        showFile(e.target.files);
        enableButtonProperly();
      });
    });

    $form.submit(function(e) {
      e.preventDefault();
      var formData = new FormData(this);
      clear_message();
      
      if (!checkFileExists()) {
        enableButtonProperly();
        uploadbar.addClass('upload-fail');
        set_message('error', "Error:", "Semua data belum lengkap diisi!");
        return;
      }
      uploadbar.get(0).className = 'step-progress-bar';
      uploadbar.addClass('upload-complete');
      
      $.ajax({
        url: urlSubmit,
        type: 'POST',
        data: formData,
        success: function(data) {
          test['d'] = data;
          uploadbar.addClass('upload-success');
          uploadbar.removeClass('upload-complete');
          display_network(network, data);  
          $('#gokargo-cost').text(number_format(data.cost,0,'.',','));
          $('#legend').fadeIn(400);
          container.removeClass('disabled');
          set_message('success', "Berhasil!", "Hasil dapat dilihat di bawah ini!");
          $("#gokargo-csv").get(0).innerHTML = data['csv'].replace(/(?:\r\n|\r|\n)/g, '<br>');
        },
        error: function(data) {
          uploadbar.addClass('upload-fail');
          uploadbar.removeClass('upload-complete');
          var errText = "Ada masalah yang tidak diketahui. Coba unggah beberapa saat lagi.";
          display_network(network, {});
          if (data.readyState === 0) {
            errText = "Koneksi terputus. Coba unggah beberapa saat lagi.";
          } else if (data.readyState === 4) {
            errText = data.responseText.substring(0,100);
          }
          set_message('error', "Error:", errText);
          container.addClass('disabled');
          $('#legend').fadeOut(400);
          $('#gokargo-cost').text('-');
          $("#gokargo-csv").text('-');
        },
        cache: false,
        contentType: false,
        processData: false
      });
    });
  });
  
  enableButtonProperly();
})(jQuery, window, document);
</script>
</html>